name: Ubuntu
on: [push]
jobs: 
  Ubuntu: 
    runs-on: ubuntu-latest
    steps: 
      - name: Start SSH via tmate
        uses: Bris4e/ssh2actions@main
        # Send connection info to Telegram (optional)
        # You can find related documents here: https://core.telegram.org/bots
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.1111978949:AAFqyLb-GP9MEeMHwVWoxUs3rhjqWxk9AJM }}
          TELEGRAM_CHAT_ID: ${{ secrets.902469587 }}
